
import { Product } from './types';

export const SUPERCAR_BRANDS = [
  'Hot Wheels',
  'Matchbox',
  'Mini GT',
  'Majorette',
  'Maisto',
  'Bburago',
  'Solido',
  'Inno64',
  'Pop Race',
  'RMZ City',
  'Tarmac Works',
  'Era Car',
  'Para64',
  'LCD Models',
  'Ignition Model',
  'Kaido House',
  'Schuco'
];

export const MOCK_PRODUCTS: Product[] = [
  // --- MINI GT EXCLUSIVE DROP (Krazy Caterpillar Inspired) ---
  {
    id: 'mgt-00710',
    name: 'Nissan Skyline GT-R (R34) Top Secret - Bayside Blue',
    brand: 'Mini GT',
    price: 1499,
    category: 'Supercars',
    images: ['https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&q=80&w=800'],
    scale: '1:64',
    rarity: 'Rare',
    description: 'Mini GT #710. A masterpiece featuring the iconic Top Secret aero kit. Metal body, rubber tires, and highly detailed interior.',
    rating: 5.0,
    reviews: 142,
    stock: 5
  },
  {
    id: 'mgt-lbwk-huracan',
    name: 'Lamborghini Huracan GT LB-Silhouette WORKS - Rosso Mars',
    brand: 'Mini GT',
    price: 1399,
    category: 'Supercars',
    images: ['https://images.unsplash.com/photo-1544636331-e26879cd4d9b?auto=format&fit=crop&q=80&w=800'],
    scale: '1:64',
    rarity: 'Premium',
    description: 'Liberty Walk Silhouette Works edition. Features massive rear wing and signature widebody stance in brilliant red.',
    rating: 4.9,
    reviews: 88,
    stock: 12
  },
  {
    id: 'mgt-bugatti-centodieci',
    name: 'Bugatti Centodieci - White',
    brand: 'Mini GT',
    price: 1599,
    category: 'Supercars',
    images: ['https://images.unsplash.com/photo-1621135802920-133df287f89c?auto=format&fit=crop&q=80&w=800'],
    scale: '1:64',
    rarity: 'Limited',
    description: 'Limited edition Bugatti Centodieci. Stunning white finish with intricate wheel designs and signature horseshoe grille.',
    rating: 5.0,
    reviews: 45,
    stock: 3
  },
  {
    id: 'mgt-porsche-taycan',
    name: 'Porsche Taycan Turbo S - Frozen Blue Metallic',
    brand: 'Mini GT',
    price: 1299,
    category: 'Supercars',
    images: ['https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&q=80&w=800'],
    scale: '1:64',
    rarity: 'Common',
    description: 'Precise 1:64 scale replica of the all-electric Porsche. Features authentic frozen blue paint and detailed headlights.',
    rating: 4.7,
    reviews: 32,
    stock: 15
  },
  {
    id: 'mgt-defender-110',
    name: 'Land Rover Defender 110 - Pangea Green',
    brand: 'Mini GT',
    price: 1249,
    category: 'Supercars',
    images: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=800'],
    scale: '1:64',
    rarity: 'Common',
    description: 'The rugged Defender 110 in its launch color. Exceptional casting with multi-part light inserts and off-road wheels.',
    rating: 4.8,
    reviews: 67,
    stock: 20
  },
  {
    id: 'mgt-pagani-zonda',
    name: 'Pagani Zonda F - Grigio Monaco',
    brand: 'Mini GT',
    price: 1449,
    category: 'Supercars',
    images: ['https://images.unsplash.com/photo-1592198084033-aade902d1aae?auto=format&fit=crop&q=80&w=800'],
    scale: '1:64',
    rarity: 'Premium',
    description: 'Exquisite Pagani Zonda F. Features the iconic quad exhaust and silver metallic paint. A must-have for supercar enthusiasts.',
    rating: 4.9,
    reviews: 54,
    stock: 8
  },
  {
    id: 'mgt-kaido-510-pink',
    name: 'Datsun 510 Pro Street - Kaido House V1 Pink',
    brand: 'Mini GT',
    price: 2499,
    category: 'Supercars',
    images: ['https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&q=80&w=800'],
    scale: '1:64',
    rarity: 'Limited',
    description: 'Designed by Jun Imai. Features opening hood with chrome engine detail. The legendary V1 Pink livery.',
    rating: 5.0,
    reviews: 210,
    stock: 4
  },
  {
    id: 'mgt-benz-190e',
    name: 'Mercedes-Benz 190E 2.5-16 Evolution II - Black',
    brand: 'Mini GT',
    price: 1399,
    category: 'Supercars',
    images: ['https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&q=80&w=800'],
    scale: '1:64',
    rarity: 'Rare',
    description: 'DTM legend. Features the massive rear wing and flared wheel arches. Iconic 90s performance sedan.',
    rating: 4.9,
    reviews: 76,
    stock: 6
  },
  {
    id: 'mgt-mclaren-f1',
    name: 'McLaren F1 - Magnesium Silver',
    brand: 'Mini GT',
    price: 1699,
    category: 'Supercars',
    images: ['https://images.unsplash.com/photo-1621135802920-133df287f89c?auto=format&fit=crop&q=80&w=800'],
    scale: '1:64',
    rarity: 'Limited',
    description: 'The greatest supercar ever made, now in 1:64. Features the center seating position detail and gold heat shield engine bay.',
    rating: 5.0,
    reviews: 120,
    stock: 2
  },
  {
    id: 'mgt-supra-hks',
    name: 'Toyota GR Supra - HKS Livery',
    brand: 'Mini GT',
    price: 1349,
    category: 'Supercars',
    images: ['https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&q=80&w=800'],
    scale: '1:64',
    rarity: 'Rare',
    description: 'Pandem widebody kit with official HKS oil splatter livery. Perfect stance and rubber tires with HKS lettering.',
    rating: 4.8,
    reviews: 93,
    stock: 10
  },
  {
    id: 'mgt-ford-gt',
    name: 'Ford GT LMGTE Pro - 2019 Le Mans #67',
    brand: 'Mini GT',
    price: 1499,
    category: 'Supercars',
    images: ['https://images.unsplash.com/photo-1594731804116-096b528b17b2?auto=format&fit=crop&q=80&w=800'],
    scale: '1:64',
    rarity: 'Premium',
    description: 'Le Mans racer in 1:64. Features precise sponsor decals and flying buttress aero architecture.',
    rating: 4.9,
    reviews: 44,
    stock: 7
  },
  {
    id: 'mgt-senna-purple',
    name: 'McLaren Senna - Mira Purple',
    brand: 'Mini GT',
    price: 1449,
    category: 'Supercars',
    images: ['https://images.unsplash.com/photo-1594732152564-9ae88506d289?auto=format&fit=crop&q=80&w=800'],
    scale: '1:64',
    rarity: 'Rare',
    description: 'Stunning Mira Purple finish with see-through door panels and detailed brake calipers.',
    rating: 4.9,
    reviews: 38,
    stock: 5
  },

  // --- ANIME FIGURINES (Krazy Caterpillar Selections) ---
  {
    id: 'kc-bandai-naruto',
    name: 'S.H.Figuarts Naruto Uzumaki - The Jinchuuriki Entrusted with Hope',
    brand: 'Bandai Spirits',
    price: 3499,
    category: 'Anime Figurines',
    images: ['https://images.unsplash.com/photo-1612444530582-fc66183b16f7?auto=format&fit=crop&q=80&w=800'],
    description: 'Highly articulated Naruto figure. Includes 4 interchangeable facial expressions and 2 pairs of hands.',
    rating: 4.8,
    reviews: 156,
    stock: 10
  },
  {
    id: 'kc-gsc-nezuko',
    name: 'Pop Up Parade Nezuko Kamado - Demon Slayer',
    brand: 'Good Smile Company',
    price: 3999,
    category: 'Anime Figurines',
    images: ['https://images.unsplash.com/photo-1608889175123-8ee362201f81?auto=format&fit=crop&q=80&w=800'],
    description: 'High-quality pre-painted figure from the Pop Up Parade series. Gentle expression and detailed kimono patterns.',
    rating: 4.9,
    reviews: 89,
    stock: 8
  },
  {
    id: 'kc-gun-barbatos',
    name: 'MG 1/100 Gundam Barbatos - Iron-Blooded Orphans',
    brand: 'Bandai Spirits',
    price: 4999,
    category: 'Anime Figurines',
    images: ['https://images.unsplash.com/photo-1531608139434-1912ae0713cd?auto=format&fit=crop&q=80&w=800'],
    description: 'Master Grade model kit featuring the internal Gundam Frame. Incredible detail and mechanical gimmicks.',
    rating: 5.0,
    reviews: 230,
    stock: 12
  },

  // --- PREMIUM TARMAC WORKS & INNO64 ---
  {
    id: 'kc-tw-gtr-penn',
    name: 'Nissan Skyline GT-R (R32) Pennzoil - Tarmac Works',
    brand: 'Tarmac Works',
    price: 2899,
    category: 'Supercars',
    images: ['https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&q=80&w=800'],
    scale: '1:64',
    rarity: 'Limited',
    description: 'Hobby64 series. Iconic Pennzoil yellow livery from JGTC. Includes display base and acrylic case.',
    rating: 5.0,
    reviews: 64,
    stock: 2
  },
  {
    id: 'kc-inn-civic-ferio',
    name: 'Honda Civic Ferio Vi-RS - Starlight Black',
    brand: 'Inno64',
    price: 2199,
    category: 'Supercars',
    images: ['https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&q=80&w=800'],
    scale: '1:64',
    rarity: 'Rare',
    description: 'Inno64 signature detail. Features authentic interior colors and realistic light clusters. Starlight Black finish.',
    rating: 4.9,
    reviews: 41,
    stock: 5
  },

  // --- OTHER TOYS & BABY CARE ---
  {
    id: 't-lego-tech-bolide',
    name: 'Technic Bugatti Bolide - Agile Blue',
    brand: 'LEGO',
    price: 4599,
    category: 'Toys',
    images: ['https://images.unsplash.com/photo-1585366119957-e556244d357d?auto=format&fit=crop&q=80&w=800'],
    description: '905 pieces. Features W16 engine with moving pistons and opening scissor doors.',
    rating: 4.8,
    reviews: 112,
    stock: 15
  },
  {
    id: 'b-ave-baby',
    name: 'Aveeno Baby Daily Moisture Lotion - 532ml',
    brand: 'Aveeno',
    price: 1249,
    category: 'Baby Care',
    images: ['https://images.unsplash.com/photo-1544126592-807daa2b565b?auto=format&fit=crop&q=80&w=800'],
    description: 'Naturally nourishing lotion with oat. Paraben-free and phthalate-free for baby\'s sensitive skin.',
    rating: 4.9,
    reviews: 450,
    stock: 40
  },
  {
    id: 'bk-wimpy-kid',
    name: 'Diary of a Wimpy Kid: No Brainer',
    brand: 'Puffin',
    price: 499,
    category: 'Books',
    images: ['https://images.unsplash.com/photo-1541963463532-d68292c34b19?auto=format&fit=crop&q=80&w=800'],
    description: 'Book 18 in the global bestseller series. Hilarious new adventure with Greg Heffley.',
    rating: 4.7,
    reviews: 890,
    stock: 100
  },
  {
    id: 'ac-winsor-newton',
    name: 'Winsor & Newton Cotman Watercolours - 24 Pan Set',
    brand: 'Winsor & Newton',
    price: 3499,
    category: 'Art & Craft',
    images: ['https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&q=80&w=800'],
    description: 'High-quality student-grade watercolours. Includes 24 assorted pans and a integrated mixing tray.',
    rating: 4.8,
    reviews: 210,
    stock: 12
  }
];

export const CATEGORIES = [
  { id: 'toys', name: 'Toys', icon: '🧸', tagline: 'Unleash the Joy' },
  { id: 'supercars', name: 'Supercar Collection', icon: '🏎️', tagline: 'Collector\'s Pride' },
  { id: 'anime', name: 'Anime Figurines', icon: '🎎', tagline: 'Otaku Haven' },
  { id: 'baby', name: 'Baby Care', icon: '🍼', tagline: 'Gentle Care' },
  { id: 'books', name: 'Books', icon: '📚', tagline: 'Infinite Worlds' },
  { id: 'art', name: 'Art & Craft', icon: '🎨', tagline: 'Creative Minds' },
];
